# Nettoyage NLP - Prétraitement des Textes

Notebook simple pour débutants : nettoyage et préparation des textes

## 1. Import des bibliothèques

In [2]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Télécharger les données nécessaires pour NLTK (à exécuter une fois)
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

# Charger les données
df = pd.read_csv('../data/processed/clean1.csv')

# Afficher un exemple de texte
print("Exemple de texte brut:")
print(df['body'].iloc[0][:200])

[nltk_data] Downloading package punkt to /home/rachid/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /home/rachid/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /home/rachid/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

Exemple de texte brut:
Die Datenanalyse-Plattform brach unerwartet ab, da die Speicheroberfläche zu gering war. Ich habe versucht, Laravel 8 und meinen MacBook Pro neu zu starten, aber das Problem behält sich bei. Ich benöt

In [3]:
df.head()

,subject,body,answer,type,queue,priority,language,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8,body_length,subject_clean,body_clean,text_combined
0,Unvorhergesehener Absturz der Datenanalyse-Pla...,Die Datenanalyse-Plattform brach unerwartet ab...,Ich werde Ihnen bei der Lösung des Problems he...,Incident,General Inquiry,low,de,Crash,Technical,Bug,Hardware,Resolution,Outage,Documentation,NaN,252,Unvorhergesehener Absturz der Datenanalyse-Pla...,Die Datenanalyse-Plattform brach unerwartet ab...,Unvorhergesehener Absturz der Datenanalyse-Pla...
1,Customer Support Inquiry,Seeking information on digital strategies that...,We offer a variety of digital strategies and s...,Request,Customer Service,medium,en,Feedback,Sales,IT,Tech Support,NaN,NaN,NaN,NaN,225,Customer Support Inquiry,Seeking information on digital strategies that...,Customer Support Inquiry Seeking information o...
2,Data Analytics for Investment,I am contacting you to request information on ...,I am here to assist you with data analytics to...,Request,Customer Service,medium,en,Technical,Product,Guidance,Documentation,Performance,Feature,NaN,NaN,696,Data Analytics for Investment,I am contacting you to request information on ...,Data Analytics for Investment I am contacting ...
3,Krankenhaus-Dienstleistung-Problem,Ein Medien-Daten-Sperrverhalten trat aufgrund ...,Zurück zur E-Mail-Beschwerde über den Sperrver...,Incident,Customer Service,high,de,Security,Breach,Login,Maintenance,Incident,Resolution,Feedback,NaN,221,Krankenhaus-Dienstleistung-Problem,Ein Medien-Daten-Sperrverhalten trat aufgrund ...,Krankenhaus-Dienstleistung-Problem Ein Medien-...
4,Security,"Dear Customer Support, I am reaching out to in...","Dear [name], we take the security of medical d...",Request,Customer Service,medium,en,Security,Customer,Compliance,Breach,Documentation,Guidance,NaN,NaN,675,Security,"Dear Customer Support, I am reaching out to in...","Security Dear Customer Support, I am reaching ..."

## 2. Normalisation (minuscules)

In [4]:
# Convertir tout en minuscules
# Exemple: "Hello World" devient "hello world"

texte_exemple = "Hello World! This Is An EXAMPLE."
texte_minuscule = texte_exemple.lower()

print("Avant normalisation:")
print(texte_exemple)
print()
print("Après normalisation (minuscules):")
print(texte_minuscule)

Avant normalisation:
Hello World! This Is An EXAMPLE.

Après normalisation (minuscules):
hello world! this is an example.

In [5]:
# Appliquer sur nos données
df['text_clean'] = df['body'].fillna('').str.lower()

print("Exemple après normalisation:")
print(df['text_clean'].iloc[0][:200])

Exemple après normalisation:
die datenanalyse-plattform brach unerwartet ab, da die speicheroberfläche zu gering war. ich habe versucht, laravel 8 und meinen macbook pro neu zu starten, aber das problem behält sich bei. ich benöt

## 3. Suppression de la ponctuation

In [6]:
# Supprimer la ponctuation
# On garde seulement les lettres et les chiffres

texte_exemple = "Hello, world! How are you? I'm fine, thanks..."

# Remplacer tout ce qui n'est pas lettre ou chiffre par un espace
texte_sans_ponctuation = re.sub(r'[^a-zA-Z0-9\s]', ' ', texte_exemple)

print("Avant suppression:")
print(texte_exemple)
print()
print("Après suppression de ponctuation:")
print(texte_sans_ponctuation)

Avant suppression:
Hello, world! How are you? I'm fine, thanks...

Après suppression de ponctuation:
Hello  world  How are you  I m fine  thanks

In [7]:
# Fonction pour supprimer la ponctuation
def remove_punctuation(text):
    """Supprimer la ponctuation d'un texte"""
    return re.sub(r'[^a-zA-Z0-9\s]', ' ', text)

# Appliquer sur nos données
df['text_clean'] = df['text_clean'].apply(remove_punctuation)

print("Exemple après suppression de ponctuation:")
print(df['text_clean'].iloc[0][:200])

Exemple après suppression de ponctuation:
die datenanalyse plattform brach unerwartet ab  da die speicheroberfl che zu gering war  ich habe versucht  laravel 8 und meinen macbook pro neu zu starten  aber das problem beh lt sich bei  ich ben t

## 4. Tokenisation

In [8]:
# Tokenisation = découper le texte en mots
# Exemple: "hello world" devient ["hello", "world"]

texte_exemple = "hello world how are you"
tokens = word_tokenize(texte_exemple)

print("Texte original:")
print(texte_exemple)
print()
print("Tokens (mots):")
print(tokens)
print(f"Nombre de mots: {len(tokens)}")

Texte original:
hello world how are you

Tokens (mots):
['hello', 'world', 'how', 'are', 'you']
Nombre de mots: 5

In [9]:
# Appliquer la tokenisation sur nos données
df['tokens'] = df['text_clean'].apply(word_tokenize)

print("Exemple de tokens:")
print(df['tokens'].iloc[0][:20])  # Afficher les 20 premiers mots
print(f"\nNombre total de mots dans ce texte: {len(df['tokens'].iloc[0])}")

Exemple de tokens:
['die', 'datenanalyse', 'plattform', 'brach', 'unerwartet', 'ab', 'da', 'die', 'speicheroberfl', 'che', 'zu', 'gering', 'war', 'ich', 'habe', 'versucht', 'laravel', '8', 'und', 'meinen']

Nombre total de mots dans ce texte: 43

## 5. Suppression des stopwords

In [10]:
# Stopwords = mots vides (très communs, peu informatifs)
# Exemples: the, is, at, which, on, a, an...

# Charger les stopwords anglais
stop_words = set(stopwords.words('english'))

print("Exemples de stopwords (anglais):")
print(list(stop_words)[:20])  # Afficher 20 stopwords

Exemples de stopwords (anglais):
['doesn', 'few', 'he', 'm', 're', 'who', 'to', 'these', 'won', 'while', 'for', "needn't", 'this', 'so', "they're", 'll', "they'll", 'our', 'but', 'will']

In [11]:
# Exemple de suppression des stopwords
texte_exemple = "the quick brown fox jumps over the lazy dog"
tokens = word_tokenize(texte_exemple)

# Garder seulement les mots qui ne sont pas des stopwords
tokens_sans_stopwords = [word for word in tokens if word not in stop_words]

print("Avant suppression des stopwords:")
print(tokens)
print()
print("Après suppression des stopwords:")
print(tokens_sans_stopwords)

Avant suppression des stopwords:
['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

Après suppression des stopwords:
['quick', 'brown', 'fox', 'jumps', 'lazy', 'dog']

In [12]:
# Fonction pour supprimer les stopwords
def remove_stopwords(tokens):
    """Supprimer les stopwords d'une liste de tokens"""
    return [word for word in tokens if word not in stop_words and len(word) > 2]

# Appliquer sur nos données
df['tokens_clean'] = df['tokens'].apply(remove_stopwords)

print("Exemple avant suppression des stopwords:")
print(df['tokens'].iloc[0][:15])
print()
print("Exemple après suppression des stopwords:")
print(df['tokens_clean'].iloc[0][:15])
print()
print(f"Nombre de mots avant: {len(df['tokens'].iloc[0])}")
print(f"Nombre de mots après: {len(df['tokens_clean'].iloc[0])}")

Exemple avant suppression des stopwords:
['die', 'datenanalyse', 'plattform', 'brach', 'unerwartet', 'ab', 'da', 'die', 'speicheroberfl', 'che', 'zu', 'gering', 'war', 'ich', 'habe']

Exemple après suppression des stopwords:
['die', 'datenanalyse', 'plattform', 'brach', 'unerwartet', 'die', 'speicheroberfl', 'che', 'gering', 'war', 'ich', 'habe', 'versucht', 'laravel', 'und']

Nombre de mots avant: 43
Nombre de mots après: 35

## 6. Pipeline complète de nettoyage

In [13]:
# Fonction complète qui fait tout le nettoyage
def clean_text(text):
    """
    Nettoyer un texte complet:
    1. Minuscules
    2. Suppression ponctuation
    3. Tokenisation
    4. Suppression stopwords
    """
    # Étape 1: Minuscules
    text = text.lower()
    
    # Étape 2: Suppression ponctuation
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    
    # Étape 3: Tokenisation
    tokens = word_tokenize(text)
    
    # Étape 4: Suppression stopwords et mots courts
    tokens = [word for word in tokens if word not in stop_words and len(word) > 2]
    
    return tokens

# Test sur un exemple
texte_test = df['body'].iloc[0]
print("Texte original:")
print(texte_test[:150])
print("\n" + "="*70 + "\n")

texte_nettoye = clean_text(texte_test)
print("Texte nettoyé (tokens):")
print(texte_nettoye[:20])

Texte original:
Die Datenanalyse-Plattform brach unerwartet ab, da die Speicheroberfläche zu gering war. Ich habe versucht, Laravel 8 und meinen MacBook Pro neu zu st

======================================================================

Texte nettoyé (tokens):
['die', 'datenanalyse', 'plattform', 'brach', 'unerwartet', 'die', 'speicheroberfl', 'che', 'gering', 'war', 'ich', 'habe', 'versucht', 'laravel', 'und', 'meinen', 'macbook', 'pro', 'neu', 'starten']

In [14]:
# Appliquer sur tous les textes
print("Application du nettoyage sur tous les tickets...")
df['text_cleaned'] = df['body'].fillna('').apply(clean_text)

# Convertir les tokens en texte (pour certains modèles)
df['text_final'] = df['text_cleaned'].apply(lambda x: ' '.join(x))

print("\nAperçu des résultats:")
print("="*70)
for i in range(3):
    print(f"\nTicket {i+1}:")
    print(f"Original: {df['body'].iloc[i][:100]}...")
    print(f"Nettoyé:  {df['text_final'].iloc[i][:100]}...")

Application du nettoyage sur tous les tickets...

Aperçu des résultats:
======================================================================

Ticket 1:
Original: Die Datenanalyse-Plattform brach unerwartet ab, da die Speicheroberfläche zu gering war. Ich habe ve...
Nettoyé:  die datenanalyse plattform brach unerwartet die speicheroberfl che gering war ich habe versucht lara...

Ticket 2:
Original: Seeking information on digital strategies that can aid in brand growth and details on the available ...
Nettoyé:  seeking information digital strategies aid brand growth details available services looking forward l...

Ticket 3:
Original: I am contacting you to request information on data analytics tools that can be utilized with the Ecl...
Nettoyé:  contacting request information data analytics tools utilized eclipse ide enhancing investment optimi...

## 7. Sauvegarde des données nettoyées

In [15]:
# Sauvegarder le DataFrame avec les textes nettoyés
# Décommenter pour sauvegarder

df[['type', 'text_final', 'tokens_clean']].to_csv('../data/processed/clean2.csv', index=False)
print("Données sauvegardées dans: ../data/processed/clean2.csv")

print("Colonnes disponibles:")
print(df[['type', 'text_final']].head())

Données sauvegardées dans: ../data/processed/clean2.csv
Colonnes disponibles:
       type                                         text_final
0  Incident  die datenanalyse plattform brach unerwartet di...
1   Request  seeking information digital strategies aid bra...
2   Request  contacting request information data analytics ...
3  Incident  ein medien daten sperrverhalten trat aufgrund ...
4   Request  dear customer support reaching inquire securit...

In [16]:
df.head()

,subject,body,answer,type,queue,priority,language,tag_1,tag_2,tag_3,...,tag_8,body_length,subject_clean,body_clean,text_combined,text_clean,tokens,tokens_clean,text_cleaned,text_final
0,Unvorhergesehener Absturz der Datenanalyse-Pla...,Die Datenanalyse-Plattform brach unerwartet ab...,Ich werde Ihnen bei der Lösung des Problems he...,Incident,General Inquiry,low,de,Crash,Technical,Bug,...,NaN,252,Unvorhergesehener Absturz der Datenanalyse-Pla...,Die Datenanalyse-Plattform brach unerwartet ab...,Unvorhergesehener Absturz der Datenanalyse-Pla...,die datenanalyse plattform brach unerwartet ab...,"[die, datenanalyse, plattform, brach, unerwart...","[die, datenanalyse, plattform, brach, unerwart...","[die, datenanalyse, plattform, brach, unerwart...",die datenanalyse plattform brach unerwartet di...
1,Customer Support Inquiry,Seeking information on digital strategies that...,We offer a variety of digital strategies and s...,Request,Customer Service,medium,en,Feedback,Sales,IT,...,NaN,225,Customer Support Inquiry,Seeking information on digital strategies that...,Customer Support Inquiry Seeking information o...,seeking information on digital strategies that...,"[seeking, information, on, digital, strategies...","[seeking, information, digital, strategies, ai...","[seeking, information, digital, strategies, ai...",seeking information digital strategies aid bra...
2,Data Analytics for Investment,I am contacting you to request information on ...,I am here to assist you with data analytics to...,Request,Customer Service,medium,en,Technical,Product,Guidance,...,NaN,696,Data Analytics for Investment,I am contacting you to request information on ...,Data Analytics for Investment I am contacting ...,i am contacting you to request information on ...,"[i, am, contacting, you, to, request, informat...","[contacting, request, information, data, analy...","[contacting, request, information, data, analy...",contacting request information data analytics ...
3,Krankenhaus-Dienstleistung-Problem,Ein Medien-Daten-Sperrverhalten trat aufgrund ...,Zurück zur E-Mail-Beschwerde über den Sperrver...,Incident,Customer Service,high,de,Security,Breach,Login,...,NaN,221,Krankenhaus-Dienstleistung-Problem,Ein Medien-Daten-Sperrverhalten trat aufgrund ...,Krankenhaus-Dienstleistung-Problem Ein Medien-...,ein medien daten sperrverhalten trat aufgrund ...,"[ein, medien, daten, sperrverhalten, trat, auf...","[ein, medien, daten, sperrverhalten, trat, auf...","[ein, medien, daten, sperrverhalten, trat, auf...",ein medien daten sperrverhalten trat aufgrund ...
4,Security,"Dear Customer Support, I am reaching out to in...","Dear [name], we take the security of medical d...",Request,Customer Service,medium,en,Security,Customer,Compliance,...,NaN,675,Security,"Dear Customer Support, I am reaching out to in...","Security Dear Customer Support, I am reaching ...",dear customer support i am reaching out to in...,"[dear, customer, support, i, am, reaching, out...","[dear, customer, support, reaching, inquire, s...","[dear, customer, support, reaching, inquire, s...",dear customer support reaching inquire securit...

## 7. Sauvegarde des données nettoyées juste best features :

In [21]:
df_final = df[['type', 'text_final']]
df_final.to_csv('../data/processed/clean3.csv', index=False)
df_final.head()
df_final.count()

type          20000
text_final    20000
dtype: int64